Improve topic name support
eclipse-cyclonedds/cyclonedds pull request #1426
Opened 2022-10-01 15:13 UTC by clunietp

The DDS Spec does not explicitly specify what constitutes a valid name.
Per https://github.com/eclipse-cyclonedds/cyclonedds/issues/1393#issuecomment-1248936537
"we require isprint is true and not , " or ' for the time being, then work our way to supporting UTF-8"

Resolves https://github.com/eclipse-cyclonedds/cyclonedds/issues/1393

2022-10-03 09:39 UTC, thijsmie requested changes
I like the changes, but perhaps it is wise to forbid the characters of `fnmatch` with an eye on future topic filtering expressions. This would be `*?[]`. I guess the topic is not a match expression so having these characters can't actually hurt, I simply think that topic names as `room.temperature.*` look extremely confusing. Maybe also with an eye on our sister project Zenoh it is also wise to forbid the Zenoh key expression special characters `#$?*`. What do you thing @eboasson?

2022-10-06 16:59 UTC, eboasson commented
> I like the changes, but perhaps it is wise to forbid the characters of `fnmatch` with an eye on future topic filtering expressions. This would be `*?[]`. I guess the topic is not a match expression so having these characters can't actually hurt, I simply think that topic names as `room.temperature.*` look extremely confusing. Maybe also with an eye on our sister project Zenoh it is also wise to forbid the Zenoh key expression special characters `#$?*`. What do you thing @eboasson?

I think you're making an very good point. Should've thought about it myself ... 🤦‍♀️

2022-10-06 17:57 UTC, clunietp commented
I'm happy to make the requested changes to the topic name filter.  My only input here is that this restriction may cause issues in the future with interoperability.  For example, both Fast-DDS 2.5 and Connext 6.1 both gladly support the creation of the topic named `Hello *?[]'"\tWorld`  (just tested)

I'm not saying that creating topic names in this format is anywhere close to a good idea (at least in my mind), but there are likely use cases that I'm unaware of where some subset of these restricted characters actually makes sense and would be considered valid.  This would necessitate a future workaround/PR, similar to the issues I had when I originally created this PR.

As an alternative to restricting the topic names any more than necessary at this point, perhaps future work with `fnmatch` (which I admittedly know nothing about) would support the use of escape characters (or some other mechanism) for topic matching with special characters and/or UTF8 chars within the topic name.  

Thoughts?

2022-10-07 07:49 UTC, eboasson commented
I'd like Cyclone to put up no barriers other than those for which there exist good engineering reasons. Requiring topic names to be ASCII really is a barrier to people living in other parts of the world, and I think we need to support them. (I think that's a pretty non-controversial position 🙂.)

In practice that means we will have to accept nearly any byte sequence as a name, while strongly suggesting that these byte strings be valid UTF-8 strings. Actually validating it is way out of scope for an embedded library like Cyclone, it pulls in too much code, makes it dependent on Unicode revisions, ... This is of course a pretty standard.

What I would *also* like is log files to be fairly easy to search through and take apart with regular expressions. (Granted, my definition of "easy" is of [doubtful quality](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/src/tools/decode-trace) in this matter.) The way I see it, that means: an easy way of knowing where a name begins and ends, and that either means forbidding some characters or escaping some in the trace output. Getting the latter right means some thinking.

There are also some other parts in the code/configuration where a few things will have to be changed. For example, the network partition configuration & matching.

Hence the proposal to do it in two steps, first we go from whitelisting some characters to allowing all printable ASCII with a few disallowed characters, and then @thijsmie is right that the characters that play a role in wildcard matching are also best excluded. That should alleviate some issues today.

Then we do a follow-up where we lift all restrictions, escape names in the output and address any other things that need changing.

2022-10-10 07:18 UTC, thijsmie approved these changes
Thanks @clunietp for making the requested changes :smile:, LGTM!

2022-10-10 09:50 UTC, merged