Update Zephyr port to support Zephyr V3.4
eclipse-cyclonedds/cyclonedds pull request #1770
Opened 2023-07-17 14:34 UTC by PatrickM-ZS

Updates related to changes introduced in Zephyr v3.4:
- Change API for maddr join/leave functions (zephyrproject-rtos/zephyr@ff0fd2d7a7)
- Change main function return type from `void` to `int` (zephyrproject-rtos/zephyr#54628)
- Allow the use of SCHED_OTHER class and verify thread priorities are inside min/max range (zephyrproject-rtos/zephyr#57161).
- Fix issue caused by the refactoring in #1742
- Add a device-tree overlay for s32z270dc2_rtu0_r52 board to increase SRAM size without needing to change any Zephyr defaults

Besides these, added some clarifications in the README.md based on user feedback.

2023-07-17 15:41 UTC, ambroise-arm requested changes

2023-07-17 15:41 UTC, ambroise-arm commented on ports/zephyr/README.md
> +Getting Started with Zephyr information can be found [here](https://docs.zephyrproject.org/latest/develop/getting_started/index.html)
Shouldn't we point to the version of the Zephyr documentation that is currently supported instead of `latest`? It will need to be updated on further version updates, but it ensures the link doesn't break and that the external information doesn't get out of date compared to this document. (same for the other links in the PR)

2023-07-17 15:41 UTC, ambroise-arm commented on ports/zephyr/README.md
> +## Usage:
There is usually no punctuation in titles

2023-07-17 15:41 UTC, ambroise-arm commented on ports/zephyr/README.md
> +The applications can be treated similar to other Zephyr sample applications.
> can be treated similar to

"similarly to"?

2023-07-17 15:41 UTC, ambroise-arm commented on ports/zephyr/README.md
> +:warning: While CycloneDDS can be built in-tree, it does not support multiple different builds. Therefore the CycloneDDS source directory needs to be clean in order to build for Zephyr and must not c
> needs to be clean

"cleaned"?

2023-07-17 15:56 UTC, PatrickM-ZS commented on ports/zephyr/README.md
> +Getting Started with Zephyr information can be found [here](https://docs.zephyrproject.org/latest/develop/getting_started/index.html)
I see your point but linking to an 'old' version also implies newer versions are not supported, while they may just work as-is. We intent for latest CycloneDDS version to always work with latest Zephyr version.

2023-07-17 16:32 UTC, PatrickM-ZS commented on ports/zephyr/README.md
> +## Usage:
Fixed!

2023-07-17 16:32 UTC, PatrickM-ZS commented on ports/zephyr/README.md
> +:warning: While CycloneDDS can be built in-tree, it does not support multiple different builds. Therefore the CycloneDDS source directory needs to be clean in order to build for Zephyr and must not c
Fixed!

2023-07-17 16:32 UTC, PatrickM-ZS commented on ports/zephyr/README.md
> +The applications can be treated similar to other Zephyr sample applications.
Fixed!

2023-07-24 11:55 UTC, eboasson commented on ports/zephyr/README.md
> +Getting Started with Zephyr information can be found [here](https://docs.zephyrproject.org/latest/develop/getting_started/index.html)
If I understand correctly, details in Zephyr change often enough that even a minor version change can already affect the port. So I have to agree with @ambroise-arm here, it makes sense to link to the latest version of Zephyr for which the port has been validated. I don't see a problem with (also) noting that it is likely to work on later versions, or something of the sort.

Having a versioned (and stable) documentation link is fine, but I think the version number should be noted at the top-level of the readme, so more like:

> This directory contains some proof-of-concept applications that show how to build and use CycloneDDS on [Zephyr RTOS](https://www.zephyrproject.org) for a NXP X-S32Z27X-DC board. We aim for compatibility with the latest release of Zephyr, at the time of writing this is version 3.3.

(Or something along those lines)

2023-07-24 11:55 UTC, eboasson commented on src/ddsrt/src/threads/posix/threads.c
> +    }
> Would it make sense to remove the bit that makes use of pthread_self() and use the new implementation in all cases as part of this PR?

I don't think so: if I am reading it correctly, that would be a significant change in default behaviour for other POSIX platforms and hence would better be done (and debated) in a separate PR.

2023-08-03 11:23 UTC, eboasson approved these changes
LGTM, thanks @PatrickM-ZS

2023-08-03 11:23 UTC, merged